<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./models/Knight.glb --output=./src/lib/assets/Models
-->

<script lang="ts" context="module">
	let id = 0;
</script>

<script lang="ts">
	import { AnimationAction, Box3, Group, Vector3 } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import { getContext, onMount } from 'svelte';

	export const ref = new Group();

	import { models } from 'shared';
	import type { EventBus } from '$lib/components/app/Views/Combat/EventBus';
	import type { HERO_ANIMATIONS_TYPE } from '$lib/components/app/Views/Combat/animations';

	const gltf = useGltf(`${models["./Knight-transformed.glb"]}?${id++}`, { useDraco: true });

	//const gltf = useGltf(`${models.knight}?${id++}`, { useDraco: true });
	import model from "./Knight-transformed.glb?url";
	//const gltf = useGltf(`${model}?${id++}`, { useDraco: true });
	export const { actions, mixer } = useGltfAnimations<HERO_ANIMATIONS_TYPE>(gltf, ref);

	const component = forwardEventHandlers();
	const bus: EventBus<{
		characterID: number;
		action: 'attack' | 'die';
	}> = getContext('bus');

	onMount(() => {
		return () => {
			id--;
		};
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Rig">
				<T is={gltf.nodes.root} />

				<T.SkinnedMesh
					name="Knight_ArmLeft"
					geometry={gltf.nodes.Knight_ArmLeft.geometry}
					skeleton={gltf.nodes.Knight_ArmLeft.skeleton}
					material={gltf.materials.knight_texture}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_ArmRight"
					geometry={gltf.nodes.Knight_ArmRight.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_ArmRight.skeleton}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_Body"
					geometry={gltf.nodes.Knight_Body.geometry}
					skeleton={gltf.nodes.Knight_Body.skeleton}
					material={gltf.materials.knight_texture}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_Head"
					geometry={gltf.nodes.Knight_Head.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_Head.skeleton}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_LegLeft"
					geometry={gltf.nodes.Knight_LegLeft.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_LegLeft.skeleton}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_LegRight"
					geometry={gltf.nodes.Knight_LegRight.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_LegRight.skeleton}
					castShadow
					receiveShadow
				></T.SkinnedMesh>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
