<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./models/Knight.glb --output=./src/lib/assets/Models
-->

<script lang="ts" context="module">
	let id = 0;
</script>

<script lang="ts">
	import { Box3, Group, Vector3 } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { Outlines, useGltf, useGltfAnimations } from '@threlte/extras';
	import { SkeletonUtils } from 'three/examples/jsm/Addons.js';
	import { onMount } from 'svelte';

	export const ref = new Group();
	//let id = crypto.randomUUID();

	import knightModel from "$lib/assets/Models/Knight-transformed.glb?url";

	const gltf = useGltf(`${knightModel}?${id++}`, { useDraco: true });

//	const gltf = useGltf(`.storybook/Knight-transformed.glb?${id++}`, { useDraco: true });
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();

	onMount(() => {
		return () => {
			id--;
		};
	});

	actions.subscribe((value) => {
		value['Idle']?.play();
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Rig">
				<T is={gltf.nodes.root} />

				<T.SkinnedMesh
					name="Knight_ArmLeft"
					geometry={gltf.nodes.Knight_ArmLeft.geometry}
					skeleton={gltf.nodes.Knight_ArmLeft.skeleton}
					material={gltf.materials.knight_texture}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_ArmRight"
					geometry={gltf.nodes.Knight_ArmRight.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_ArmRight.skeleton}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_Body"
					geometry={gltf.nodes.Knight_Body.geometry}
					skeleton={gltf.nodes.Knight_Body.skeleton}
					material={gltf.materials.knight_texture}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_Head"
					geometry={gltf.nodes.Knight_Head.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_Head.skeleton}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_LegLeft"
					geometry={gltf.nodes.Knight_LegLeft.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_LegLeft.skeleton}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
				<T.SkinnedMesh
					name="Knight_LegRight"
					geometry={gltf.nodes.Knight_LegRight.geometry}
					material={gltf.materials.knight_texture}
					skeleton={gltf.nodes.Knight_LegRight.skeleton}
				>
					<Outlines color="white" thickness={0.02} />
				</T.SkinnedMesh>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
