<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./models/rogue/Rogue.glb --transform --output ./src/lib/assets/Models --types --shadows --simplify
-->
<script context="module" lang="ts">
	let id = 0;

</script>

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName =
    | '1H_Melee_Attack_Chop'
    | '1H_Melee_Attack_Slice_Diagonal'
    | '1H_Melee_Attack_Slice_Horizontal'
    | '1H_Melee_Attack_Stab'
    | '1H_Ranged_Aiming'
    | '1H_Ranged_Reload'
    | '1H_Ranged_Shoot'
    | '1H_Ranged_Shooting'
    | '2H_Melee_Attack_Chop'
    | '2H_Melee_Attack_Slice'
    | '2H_Melee_Attack_Spin'
    | '2H_Melee_Attack_Spinning'
    | '2H_Melee_Attack_Stab'
    | '2H_Melee_Idle'
    | '2H_Ranged_Aiming'
    | '2H_Ranged_Reload'
    | '2H_Ranged_Shoot'
    | '2H_Ranged_Shooting'
    | 'Block'
    | 'Block_Attack'
    | 'Block_Hit'
    | 'Blocking'
    | 'Cheer'
    | 'Death_A'
    | 'Death_A_Pose'
    | 'Death_B'
    | 'Death_B_Pose'
    | 'Dodge_Backward'
    | 'Dodge_Forward'
    | 'Dodge_Left'
    | 'Dodge_Right'
    | 'Dualwield_Melee_Attack_Chop'
    | 'Dualwield_Melee_Attack_Slice'
    | 'Dualwield_Melee_Attack_Stab'
    | 'Hit_A'
    | 'Hit_B'
    | 'Idle'
    | 'Interact'
    | 'Jump_Full_Long'
    | 'Jump_Full_Short'
    | 'Jump_Idle'
    | 'Jump_Land'
    | 'Jump_Start'
    | 'Lie_Down'
    | 'Lie_Idle'
    | 'Lie_Pose'
    | 'Lie_StandUp'
    | 'PickUp'
    | 'Running_A'
    | 'Running_B'
    | 'Running_Strafe_Left'
    | 'Running_Strafe_Right'
    | 'Sit_Chair_Down'
    | 'Sit_Chair_Idle'
    | 'Sit_Chair_Pose'
    | 'Sit_Chair_StandUp'
    | 'Sit_Floor_Down'
    | 'Sit_Floor_Idle'
    | 'Sit_Floor_Pose'
    | 'Sit_Floor_StandUp'
    | 'Spellcast_Long'
    | 'Spellcast_Raise'
    | 'Spellcast_Shoot'
    | 'Spellcasting'
    | 'T-Pose'
    | 'Throw'
    | 'Unarmed_Idle'
    | 'Unarmed_Melee_Attack_Kick'
    | 'Unarmed_Melee_Attack_Punch_A'
    | 'Unarmed_Melee_Attack_Punch_B'
    | 'Unarmed_Pose'
    | 'Use_Item'
    | 'Walking_A'
    | 'Walking_B'
    | 'Walking_Backwards'
    | 'Walking_C'
  type GLTFResult = {
    nodes: {
      Knife_Offhand: THREE.Mesh
      Knife: THREE.Mesh
      ['1H_Crossbow']: THREE.Mesh
      ['2H_Crossbow']: THREE.Mesh
      Throwable: THREE.Mesh
      Rogue_Cape: THREE.Mesh
      Rogue_ArmLeft: THREE.SkinnedMesh
      Rogue_ArmRight: THREE.SkinnedMesh
      Rogue_Body: THREE.SkinnedMesh
      Rogue_Head: THREE.SkinnedMesh
      Rogue_LegLeft: THREE.SkinnedMesh
      Rogue_LegRight: THREE.SkinnedMesh
      root: THREE.Bone
    }
    materials: {
      rogue_texture: THREE.MeshStandardMaterial
      rogue_texture: THREE.MeshStandardMaterial
    }
  }
	import { models } from 'shared';
	import { onMount } from 'svelte';

  // const gltf = useGltf<GLTFResult>('/Rogue-transformed.glb', { useDraco: true })
  	const gltf = useGltf(`${models['./Rogue-transformed.glb']}?${id++}`, { useDraco: true });

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()


	onMount(() => {
		return () => {
			id--;
		};
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Rig">
        <T is={gltf.nodes.root} />
        <T.SkinnedMesh
          name="Rogue_ArmLeft"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_ArmLeft.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_ArmLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Rogue_ArmRight"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_ArmRight.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_ArmRight.skeleton}
        />
        <T.SkinnedMesh
          name="Rogue_Body"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_Body.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_Body.skeleton}
        />
        <T.SkinnedMesh
          name="Rogue_Head"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_Head.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_Head.skeleton}
        />
        <T.SkinnedMesh
          name="Rogue_LegLeft"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_LegLeft.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_LegLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Rogue_LegRight"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Rogue_LegRight.geometry}
          material={gltf.materials.rogue_texture}
          skeleton={gltf.nodes.Rogue_LegRight.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
