<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./models/Knight.glb --output=./src/lib/assets/Models
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Knight.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Rig">
        <T is={gltf.nodes.root} />
        <T.SkinnedMesh
          name="Knight_ArmLeft"
          geometry={gltf.nodes.Knight_ArmLeft.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_ArmLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Knight_ArmRight"
          geometry={gltf.nodes.Knight_ArmRight.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_ArmRight.skeleton}
        />
        <T.SkinnedMesh
          name="Knight_Body"
          geometry={gltf.nodes.Knight_Body.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_Body.skeleton}
        />
        <T.SkinnedMesh
          name="Knight_Head"
          geometry={gltf.nodes.Knight_Head.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_Head.skeleton}
        />
        <T.SkinnedMesh
          name="Knight_LegLeft"
          geometry={gltf.nodes.Knight_LegLeft.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_LegLeft.skeleton}
        />
        <T.SkinnedMesh
          name="Knight_LegRight"
          geometry={gltf.nodes.Knight_LegRight.geometry}
          material={gltf.materials.knight_texture}
          skeleton={gltf.nodes.Knight_LegRight.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
